plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - ".bundle/**/*"
    - "coverage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 3

Style/Documentation:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: single_quotes
